a=list()
print("list is ",a)
print("Id of the list is",id(a))
print("type of the list is",type(a))
a.append(100)
print("list is ",a)
print("Id of the list is",id(a))
print("type of the list is",type(a))